---
# tasks file for amee_platform

- include: java_app.yml
- include: nginx.yml
- include: message_queue.yml
- include: php.yml

- name: put platform start file on the platform
  template: >
    src=init.sh.j2
    dest="/etc/init.d/{{ platform_app }}"
    mode=0644
  tags: services
