- name: add rabbitmq
  apt: name=rabbitmq-server state=present

# - name: allow management of the box via the web
#   command: rabbitmq-plugins enable rabbitmq_management

- name: setup our rabbitMQ user
  rabbitmq_user: >
    user={{ platform_mq_user }}
    password={{ platform_mq_user_password }}
    state=present
    configure_priv=.*
    read_priv=.*
    write_priv=.*
