- name: install nginx
  apt: name=nginx state=present
  tags:
    - nginx

- name: add certificate for serving SSL
  copy: >
    src={{ platform_ngx_ssl_cert_file }}
    dest={{ platform_ngx_ssl_cert_path }}
    backup=yes
  tags:
    - nginx

- name: add accompanying key files for serving SSL
  copy: >
    src={{ platform_ngx_ssl_key_file }}
    dest={{ platform_ngx_ssl_key_path }}
    backup=yes
  tags:
    - nginx

- name: add amee nginx vhost config
  template: >
    src="amee_platform.nginx.conf.j2"
    dest="/etc/nginx/sites-enabled/{{ platform_app }}"
  notify: restart nginx
  tags:
    - nginx
    - restart
