---
# handlers file for amee_platform
- name: restart nginx
  sudo: yes
  service: name=nginx state=restarted

- name: reload nginx
  sudo: yes
  service: name=postgresql state=reloaded

- name: restart amee
  sudo: yes
  service: name={{ platform_app }} state=restarted sleep=2
